docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
    - Configuration: config.md
    - "Debug Provider": debug.md
site_name: 'phly'
site_description: 'league/oauth2-client adapter for zend-expressive-authentication'
repo_url: 'https://github.com/phly/phly-expressive-oauth2clientauthentication'
copyright: 'Copyright (c) 2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
